### ISSUE TITLE
This data showing huge spikes - discrepancy from state and public data

### ISSUE THREAD

**Issue by samuelmstern** [MickeyLane/ByZip#1]
I'm at a loss to decipher the data. When comparing the data, from day to day, it some times zip codes with huge spikes and large number of positives, diverging dramatically from city and state reports. Can you explain what the total data, uploaded daily, means. Does this reflect any historic numbers added on that date?

**Comment by samuelmstern** [comment]
I can share examples if that will help.

**Comment by samuelmstern** [comment]
I was referring to New York City data. There are discrepancy between city and what NY State is reporting. I thought that you are familiar with the data sources. Thank you

**Comment by MickeyLane** [comment]
For NYC, I pull from GitHub nychealth/coronoavirus-data, use git log to make sure what commit I'm working with and then copy the file data-by-modzcta.csv into my ByZip\NewYork\2020-xx-xx directory.

If I miss a day, I checkout whatever that day was and copy that file too.

I don't do anything at all to any of it.
